<?php

namespace BlogBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findArticlesWhereTitleInclude($title)
    {
        $articles = $this->getEntityManager()->createQuery(
                        'SELECT a FROM BlogBundle:Article a
                        WHERE a.title LIKE :title')
                        ->setParameter('title', '%' . $title . '%')->getResult();

        return $articles;
    }
}
