<?php

namespace BlogBundle\Repository;

/**
 * Picture_1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Picture_1Repository extends \Doctrine\ORM\EntityRepository
{
}
